const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.time
	];
};
self.C3_JsPropNameTable = [
	{time: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Bullet: 0},
	{bullet1: 0},
	{TiledBackground3: 0},
	{bullet2: 0},
	{block: 0},
	{Button: 0},
	{Sprite5: 0},
	{Keyboard: 0},
	{Text: 0},
	{Audio: 0},
	{howManyMinutesYouHaveSuffered: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	bullet1: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	bullet2: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	howManyMinutesYouHaveSuffered: class extends self.ITextInstance {}
}